services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orgalife
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
    networks:
      - proxy

networks:
  proxy:
    external: true
